### ISSUE TITLE
求开发信任帖子、封禁天数递增、加入黑名单功能

### ISSUE THREAD

**Issue by Xeonacid** [xfgryujk/TiebaManager#1]
rt 个人认为三个有用的功能
比如：
A吧水楼水贴不限制 其他贴禁水 就可以把水楼加入信任帖子里 然后把常见的水贴关键词放入违规内容 就不需要吧务手动删还可以基本避免误伤
B吧水经验第一次一天 第二次三天 第三次十天 就可以在机器里直接设置 非常方便
黑名单就不多说了 希望和封禁一样 第X次后拉黑
【我写不出代码才来发issue 如果大神不喜表喷我qwq】
最后感谢作者的无私奉献 这是我用过的功能最完善界面最友好的删帖机了
另外有没有个捐助通道神马的w

**Comment by xfgryujk** [comment]
信任帖子准备做，其他都是比较大的改动不知道什么时候有空做
咱支付宝xfgryujk@126.com，以后写在关于里吧...
