### ISSUE TITLE
期望可以全局utf-8……

### ISSUE THREAD

**Issue by bear-shen** [xfgryujk/TiebaManager#12]
主要是目前出现了一些使用utf-8字符的广告字段……
例如➊➋➌➍➎➏➐➑➒➓这样的……
而且贴吧页面现在看起来也基本都是utf-8，不知这么做是否兼容会更好一点？

**Comment by xfgryujk** [comment]
你想说的是unicode字符集吧...我源码和程序都用了unicode的啊

**Comment by xfgryujk** [comment]
好吧，XML的编码是GBK，要改很麻烦，可以用正则表达式转义编码...

**Comment by tjsky** [comment]
正则转义吧，
目前我是这么搞的。
