### ISSUE TITLE
偶发针对某个用户只删帖不封禁

### ISSUE THREAD

**Issue by CharlesChou73** [xfgryujk/TiebaManager#16]
设置了删帖并封禁
1月7日晚软件连续删除违规贴，并没有封禁发帖用户
查看其中一个违规贴，查询后台记录，该用户最后被封禁是在1月4日，封禁一天（使用软件封禁）
在网页端手动封禁该用户
在设置中取消封禁选项，保存设置，再勾选封禁，保存设置，终端显示封禁其他用户

随后检查了cache.xml的内容，个人考虑从后台获取已封禁用户列表的过程存在bug

**Comment by xfgryujk** [comment]
可能吧...
