### ISSUE TITLE
你好！感谢你的开发。

### ISSUE THREAD

**Issue by Emperorreleasedays** [xfgryujk/TiebaManager#19]
我在贴吧被骗了，现在怎么搜索发言记录呢？需要找到骗子的联系方式，没有准确方式，警察不受理…
求助技术宅！

**Comment by xfgryujk** [comment]
http://tieba.baidu.com/f/search/adv

**Comment by luciferDD** [comment]
大大…对方隐藏动态了…这个搜不到…怎么办？/(ㄒoㄒ)/~~  家里好不容易寄过来的钱…
大大有什么方法吗？

**Comment by xfgryujk** [comment]
https://www.baidu.com/s?wd=site%3Atieba.baidu.com

**Comment by Emperorreleasedays** [comment]
谢谢技术大手子！有能查绑定的方法吗？鞠躬

**Comment by xfgryujk** [comment]
没有

**Comment by Emperorreleasedays** [comment]
哭瞎…
