### ISSUE TITLE
最新版存在无故消失信任用户的问题&一些建议

### ISSUE THREAD

**Issue by Rongronggg9** [xfgryujk/TiebaManager#2]
大概就是多次修改后会出现，信任用户消失，出现部分信任帖子在列表里。也可能是修改后点关闭在弹窗里选择是导致，具体触发原因未验证，但多次换用不同姿势修改配置一定会出现此类情况【可能需要重启程序才会出现】。全程未修改过信任用户，win10 th2 10586.3
另外可否添加一个功能是部分关键词无需确认直接删除，部分关键词须确认再删除？
另另外可否添加一个在等待删帖间隔时先弹窗确认要不要删，再等待删帖？
另另另外可否添加暂停审批功能？不然等待审批的帖子多了只能上任务管理器关闭了。
还有一个我觉得也可以加进去的就是放弃删帖队列【不审批模式下】，不然看见什么不对头的又得关掉重练w
还还有就是审批弹窗对于楼中楼可否显示上下文，不然校园类贴吧有些关键词实在是不敢删w
说了好多啊ww
好像有点为难诶
慢慢来吧
什么时候我有了支付宝就支持一下你【然而我初三

**Comment by xfgryujk** [comment]
最近开的坑太多了我好方...
有时间的话看看吧...

**Comment by Rongronggg9** [comment]
好的w
