### ISSUE TITLE
期望可以追加一个错误日志/显示错误部分的功能……

### ISSUE THREAD

**Issue by bear-shen** [xfgryujk/TiebaManager#20]
![image](https://cloud.githubusercontent.com/assets/7407036/23225758/05495548-f96e-11e6-955b-7a3989599cda.png)
目前的情况是经常提示出现“正则表达式错误”……但是又无法确定到底哪一个出错了(因为正则很多，一个个定位非常麻烦)……就是说……是否可以把“正则表达式错误”这句话改成“正则表达式xxxx错误”？

另外还有一个问题是强制确认这个功能是阻塞的……也就是有帖子处在“待确认”这个状态时，接下来命中不需要强制确认的帖子需要等到确认完成才能删除……这个在发帖量较高时候会显得很麻烦…… _(:3J∠)_不知道这个……可不可以稍稍的修正一下……

**Comment by xfgryujk** [comment]
可以
