### ISSUE TITLE
交流群里大家关心的几个问题

### ISSUE THREAD

**Issue by tjsky** [xfgryujk/TiebaManager#22]
1、忽略主题，没效果忽略了还是会扫描。
2、直播贴，投票贴扫描问题（破解新版客户端接口后应该能解决吧）
3、旧版升级新版，xml声明是GBK，但实际文件是UTF-8编码的，成了乱码他们看不到，悲剧了一大片，虽然本来就要重新写规则吧。

还有个小问题，软件关于那里http://tieba.baidu.com/i/37897560 这网址现在不能这么写了吧。会跳转到登录者自己的i贴吧去的

**Comment by xfgryujk** [comment]
解决了
