### ISSUE TITLE
关于确认窗口的置顶问题

### ISSUE THREAD

**Issue by tjsky** [xfgryujk/TiebaManager#24]
群里提过几次这个问题
目前弹出窗口会自动置顶，如果正在干其他的事，
比如在打字或者玩游戏，弹出后可能正好在点空格就出现误删了。
不知道能不能实现，确认窗口可以选择置顶或不置顶。
（貌似没见过弹出窗口不置顶的情况。不知道能做到不）

PS：顺带问个自己的问题，可否加入正则匹配时，忽略字母大小写功能，
网址大小写都一样的嘛，所以目前有些广告就随机大写几个字母，正则就检测不到了。

**Comment by xfgryujk** [comment]
不想写

**Comment by xfgryujk** [comment]
忽略大小写看心情

**Comment by tjsky** [comment]
(*^__^*) 哈哈。。谢谢啦~
