### ISSUE TITLE
信任规则低概率失效问题

### ISSUE THREAD

**Issue by tjsky** [xfgryujk/TiebaManager#25]
极低几率（同时监视三个吧一直挂机大约1周有1次）扫描时会出现信任规则无效。

不太懂为什么出这个问题，从逻辑上应该不会，但实际使用时确实会有这个问题。

群里也有人反映偶尔会有信任规则失效问题。

**Comment by xfgryujk** [comment]
那我也没办法

**Comment by tjsky** [comment]
辛苦了。。。

**Comment by tjsky** [comment]
经过测试，严格说信任规则失效是这个情况。
因为某些奇怪的原因（很可能是网络）无法获取到回复的作者名或者等级等信息。
所以基于作者名或者等级的信任规则自然就没法生效。

再次说一声辛苦了(*^__^*)

**Comment by xfgryujk** [comment]
和以前一样只有帖子能获取等级

**Comment by tjsky** [comment]
就是帖子。。我测试的是我自己的帖子1~5层，不是楼中楼，
出问题时的那次扫描，帖子全都没获取到用户名。
感觉不是软件的问题，只是那一次扫描时，
返回的数据就没有等级或者用户名信息吧。
