### ISSUE TITLE
建议两只

### ISSUE THREAD

**Issue by dog194** [xfgryujk/TiebaManager#26]
1. 确认界面同时提供 log界面的楼层数，打开浏览器比较好找
2. 确认界面锁掉键盘输入，比如回车esc啥的，或者最好能添加，不然有时候打字打字，突然跳，然后误操作比较尴尬

望有空的时候瞅瞅 XD

**Comment by xfgryujk** [comment]
可以

**Comment by dog194** [comment]
建议第三只，，循环封禁插件，没有进行名字唯一检查0.0
就是输两个一样的名字好像并不会提醒。
不过这个可能比较烦，如果要更新，所以仅建议

**Comment by xfgryujk** [comment]
其实也不麻烦只是没有必要

**Comment by dog194** [comment]
啊这样啊，好的，谢谢，
主界面监控贴吧名 建议额外加一个 不循环封开始，
有时候手抖 或者程序蹦了，重启就刷一下 全部封 用户一般会知道自己上次是啥时候开启的程序 XD

**Comment by dog194** [comment]
还有判断界面可以考虑加一个 立即封禁 无视违规次数直接进入循环封了0.0

**Comment by tjsky** [comment]
确认界面，既然都提供log界面的楼层数了，
干脆把等级也显示一下。（能获取等级的就显示，不能获取的就不显示）
手动的时候多个判断条件(*^__^*)

**Comment by tjsky** [comment]
@dog194 @xfgryujk 这样如何(*^__^*) 
确认界面显示
【内容】，【作者ID】，【楼层】，【作者等级】4个内容

提供
【删除】，【忽略】，【封禁】，【循环封禁】，【浏览器查看】5个选项

**Comment by xfgryujk** [comment]
加一半吧

**Comment by dog194** [comment]
有时候扫描线程蜜汁卡死，希望能有强制停止当前扫描线程功能

**Comment by xfgryujk** [comment]
等个十几秒总会停止的

**Comment by dog194** [comment]
QAQ，，如果提示确认界面屏蔽快捷键比较麻烦，那么麻烦把焦点默认选中 浏览器 而不是  是 的按钮。。这样就算误按也仅仅是打开浏览器 而不是删帖

**Comment by xfgryujk** [comment]
我是想做成过1秒才能点是的

**Comment by dog194** [comment]
0.0 .这。。有些常见H图 1s不到就知道是要删的，延迟 反倒是不怎么好吧 0.0 我觉得。 可以考虑加一句话把焦点挪到 打开浏览器 就好了。（个人想法。最近经常码字的时候误删 T T ）

**Comment by xfgryujk** [comment]
违规帖比较多时用快捷键方便啊所以不能改

**Comment by dog194** [comment]
线程有时候真的会蜜汁卡死。。2点到早上11点 那个线程还过不去。
只能关进程。（然后缓存文件也无法保存。。）
所以 提供一个立即保存 缓存的 按钮？ 还是 提供强制停止线程的 功能？

**Comment by dog194** [comment]
还是希望能加入强制关闭线程功能。。有时候线程蜜汁卡死。停在那里超过5小时没动了。CPU 占用倒是一直在跳。强制关闭的话，cache文件又无法保存。点的一堆忽略 跟 违规计数就无法保存。。

**Comment by dog194** [comment]
建议 因为多吧发帖 而获取不到等级的 按照1级处理 0.0

**Comment by xfgryujk** [comment]
加上fid应该能获取
