### ISSUE TITLE
希望加入同时扫描昵称功能

### ISSUE THREAD

**Issue by tjsky** [xfgryujk/TiebaManager#28]
管理器用的接口看到的是用户名，而部分卖片的学会用昵称写类似
【看片找-abc1234】【加群看片12345】
的昵称，去宣传的他微信

**Comment by xfgryujk** [comment]
百度出的功能越来越傻逼

**Comment by tjsky** [comment]
╮(╯▽╰)╭，百度越来越奇葩。
现在新版客户端接口，还没发封禁了，封人封的是昵称。
幸好管理器是旧版接口
