### ISSUE TITLE
编译出错，环境VS2017

### ISSUE THREAD

**Issue by tpxxn** [xfgryujk/TiebaManager#29]

**Comment by tpxxn** [comment]
![image](https://user-images.githubusercontent.com/10829204/29419359-87b0790e-83a1-11e7-8359-311d9b9e9c9d.png)

**Comment by xfgryujk** [comment]
自己看着改改呗...

**Comment by tpxxn** [comment]
问题就在于不会c++啊。。。学c#的(*꒦ິ⌓꒦ີ)

**Comment by xfgryujk** [comment]
那几个error改成
1. `	throw std::invalid_argument("No interface");`
2. `	if (plugin.m_onConfig)`
3. 去掉整个if块

**Comment by tpxxn** [comment]
哇明天试试看，感谢Ｏ(≧▽≦)Ｏ
