### ISSUE TITLE
可能有个错误

### ISSUE THREAD

**Issue by wangddtt** [xfgryujk/TiebaManager#3]
// 验证用户权限
    // 旧接口
    //src2 = HTTPGet(_T("http://tieba.baidu.com/f/bawu/admin_group?kw=") + EncodeURI_GBK(g_forumName), FALSE);
    src2 = HTTPGet(_T("http://tieba.baidu.com/bawu2/platform/listBawuTeamInfo?word=") + g_encodedForumName + _T("&ie=utf-8"), FALSE);

用这个网址验证小吧权限，小吧多了可能会出错
例：http://tieba.baidu.com/bawu2/platform/detailsInfo?word=%E5%AE%9D%E5%89%91%E8%AE%B0%E7%9A%84%E5%A4%87%E5%BF%98%E5%BD%95&ie=utf-8

**Comment by wangddtt** [comment]
看错了，网址不一样，你那个没错

**Comment by xfgryujk** [comment]
- -看成上面那个旧接口了吧，以前有这个问题我就改了
