### ISSUE TITLE
希望加入选项可以扫描直播贴和置顶帖

### ISSUE THREAD

**Issue by tpxxn** [xfgryujk/TiebaManager#31]
研究了好几天实在看不懂C++的代码...

**Comment by xfgryujk** [comment]
置顶帖一直可以扫描啊，直播帖要选择扫描使用客户端接口才行

**Comment by tpxxn** [comment]
设定了扫描使用客户端接口每次扫描只有零点几秒，而且依旧没法扫访谈直播帖

**Comment by xfgryujk** [comment]
你在查看帖子里能看到说明能扫描，不扫描是因为没有新回复

**Comment by tpxxn** [comment]
恩....看了一下查看帖子里是有，但是没有访谈直播帖，设置了扫描使用客户端接口

**Comment by tpxxn** [comment]
![image](https://user-images.githubusercontent.com/10829204/29495529-e64807b2-85f3-11e7-81ed-3eae95a93308.png)
![image](https://user-images.githubusercontent.com/10829204/29495532-eb9ad4d8-85f3-11e7-93f9-c0fe9ceae0d3.png)

**Comment by tpxxn** [comment]
![image](https://user-images.githubusercontent.com/10829204/29495536-fa1cb030-85f3-11e7-9486-f62096fb5304.png)

**Comment by xfgryujk** [comment]
可以给个贴吧名吗

**Comment by tpxxn** [comment]
冒险岛2吧

**Comment by xfgryujk** [comment]
这个帖子现在在第3页，客户端接口获取的帖子是不会把直播帖放在第一个的
![qq 20170820221120](https://user-images.githubusercontent.com/8419596/29495613-44bf8814-85f5-11e7-8ec5-2ed2b2e3f349.png)

**Comment by tpxxn** [comment]
程序不是通过下载html然后搜索对应的div id再进行匹配违规规则的吗？
![image](https://user-images.githubusercontent.com/10829204/29495635-b852bdbe-85f5-11e7-8353-69a1b73563b7.png)

**Comment by xfgryujk** [comment]
其实也没有解析DOM，只是简单的字符串处理
不解析直播贴因为直播贴和普通帖DOM结构差太多了，而且经常变化

**Comment by tpxxn** [comment]
原来如此....那还是得去找在第几页再扫描了╮(╯﹏╰）╭ 谢谢作者耐心回答(〃'▽'〃)~

**Comment by xfgryujk** [comment]
不过有人回复直播帖还是会顶到第一页的，所以平常不用太在意

**Comment by tpxxn** [comment]
主要就是回复的比较少经常被其他帖顶到后面去...
