### ISSUE TITLE
群里的一个功能脑洞，希望可以实现

### ISSUE THREAD

**Issue by tjsky** [xfgryujk/TiebaManager#33]
目前很多色情广告都是在图片内嵌套二维码做宣传。
虽然他图片很模糊，但是用浏览器微信扫图都能正确识别二维码。
（毕竟二维码就是为了这个设计的）

能否加入这种功能

1、检测图片是否含有二维码。

2、如果是二维码，解析二维码内容。

目前的期望是可以
在【扫描】里做成一个选项【解析图片二维码】，在【图片条件】里加一个选项【检测出现二维码】

**Comment by xfgryujk** [comment]
自己编啊

**Comment by tjsky** [comment]
2333，作者大大辛苦了。

我这不是不会C艹嘛（摊手）
有功夫了研究下~谢谢啦~

**Comment by xfgryujk** [comment]
看了一下没有什么二维码广告，还是算了
