### ISSUE TITLE
客户端接口扫到特定内容会导致管理崩溃

### ISSUE THREAD

**Issue by tjsky** [xfgryujk/TiebaManager#37]
【芸4#盘】成认片 咖 【∪ℝ 8 ➑ ∪ℝ】
【芸0#】麦片  ➾【∪Ⓡ 8  ➑ ∪R】
类似这样标题，1楼为空的帖子
在使用客户端接口时，管理器会崩溃退出。

上周已经发现，但今天才确定是这种内容导致的。

**Comment by xfgryujk** [comment]
有链接或者错误提示吗

**Comment by tjsky** [comment]
就是“程序崩溃了，请把。。。帮助调戏”
昨天是群里人直接说的。

以小说吧为例，启动后，可以【确认】监控贴吧名，当设置到某一页时（这个不一定，看情况应该是某个帖子，不一定是我上边说的那个），点击【开始】后，程序奔溃。
点击【查看帖子】，当试图查看，崩溃时扫描的那一页，贴吧浏览器里什么都看不到。

根据他们的反馈，之前出现HTTPS这个问题前，是没有的，是在升级后出现的。

一个个顶贴到第一页，看顶到那个会崩溃，测试结果时
应该是这两个之一导致的。目测第一个几率大。
https://tieba.baidu.com/p/3812183138
https://tieba.baidu.com/p/4945653692

**Comment by tjsky** [comment]
真的是辛苦你了，谢谢，总是给你提各种奇奇怪怪的问题，麻烦你。

**Comment by xfgryujk** [comment]
百度总是改客户端API，莫名其妙就类型错误了...
