### ISSUE TITLE
是否考虑添加一个按钮，用于手动触发 程序关闭 事件

### ISSUE THREAD

**Issue by dog194** [xfgryujk/TiebaManager#39]
是否考虑添加一个按钮，用于手动触发 程序关闭 事件

用于 程序线程卡死后 不得不任务管理器强制关闭前 手动把cache等文件保存。

一个相对于解决卡死 折中的简易治标方案

**Comment by xfgryujk** [comment]
懒得加
以后我用python重写一遍应该没有这些问题了

**Comment by dog194** [comment]
0.0 OK 知道了
