### ISSUE TITLE
建议增加日志自动保存功能

### ISSUE THREAD

**Issue by wangddtt** [xfgryujk/TiebaManager#4]
或者退出时提示保存也行，要不误删 了不好查，谢谢

**Comment by wangddtt** [comment]
请酌情添加以下功能
1. 违规内容 导入导出功能 
2. 违规内容匹配次数统计功能（将每个违规关键字匹配次数做一个记录，以便将匹配少的去掉，关键字太多了速度慢）
3.改良图片匹配功能 （违规图片库太多了慢，而且匹配上的也不多，希望改成大图里面找小图的，也就是在贴子图片里面找特征图片，这个可以调用网上一个大漠插件里面的功能，加快开发速度，VB示例如下）
    dim dm as object
    Dim intx
    Dim inty
Set dm = CreateObject("dm.dmsoft")
  dm.BindWindow(Me.hWnd, "gdi", "normal", "normal", 0)  ‘不绑定窗口的话，在屏幕上查找
  Ret = dm.FindPic(0, 0, 900, 200, "d:\特征图片.bmp", "656565", 0.7, 0, intx, inty)

**Comment by xfgryujk** [comment]
_(:з」∠)_期末事多得一B，有空慢慢填
