### ISSUE TITLE
repo 主有没有什么获取主题的最后回复的合理方法?

### ISSUE THREAD

**Issue by Purstal** [xfgryujk/TiebaManager#40]
这个问题已经困扰了我两年多了...
自从 15~16 年左右年贴吧封掉了高级搜索可以搜到任何人贴子的 bug 后, 我就完全对楼中楼束手无策了...
新的一年到来了, 我突然想起来自己还有这么一个坑, 然后意识到我依旧无法解决这个问题, 不知 repo 主有没有什么旁门左道能分享. 感谢 repo 主.

**Comment by xfgryujk** [comment]
我要有办法就出针对挖坟的功能了...

**Comment by xfgryujk** [comment]
打算以后用python重写一遍，把所有帖子爬到数据库，然后搜索最后回复会简单很多

**Comment by Purstal** [comment]
记录贴子的最后回复日期来针对挖坟确实是个好方法.
不过把收集到的数据记录到数据库似乎也无法解决楼中楼的问题.. 一个几千回复的贴子里, 中间某层有人回复一句, 除了每次都暴力重新爬一遍整个贴子外好像真没其他方法了...
顺便安利一波 go 语言 >_>

**Comment by xfgryujk** [comment]
go凉了
