### ISSUE TITLE
昵称带 emoji 无法获取昵称

### ISSUE THREAD

**Issue by dog194** [xfgryujk/TiebaManager#42]
昵称带 emoji 无法获取昵称
例如  啥啥啥[emoji][emoji]啥啥 类似的昵称，扫的时候 名称显示 空。

**Comment by dog194** [comment]
额。不对。好像楼中楼 无法正常获取 用户名。

**Comment by xfgryujk** [comment]
换个接口呢

**Comment by dog194** [comment]
换成客户端借口扫描 现在可以正常获取 楼中楼 用户名了。
