### ISSUE TITLE
一个判断楼中楼的错误

### ISSUE THREAD

**Issue by wangddtt** [xfgryujk/TiebaManager#5]
图片示例见此贴最后一楼
http://tieba.baidu.com/p/4165621052

**Comment by xfgryujk** [comment]
那个也是帖子源码的一部分，并不是错误...

**Comment by wangddtt** [comment]
能不能稍微改进一下，不要把回复中的ID算进去？

**Comment by xfgryujk** [comment]
在正则前面加上([^"<]|^)吧

**Comment by wangddtt** [comment]
(this)" username="qq469859384" target="_blank" class
这个OK了

但这个还是不行 
username="qqaiqq1983520" target=
不过这样的比较少，估计靠改正则也没办法了

**Comment by xfgryujk** [comment]
其实还可以用信任内容
