### ISSUE TITLE
贴吧封禁其实不要求PID的

### ISSUE THREAD

**Issue by BreakshadowCN** [xfgryujk/TiebaManager#6]
pid可以任意填写，uid和user_name对了就行。或者用wap、客户端接口……

**Comment by xfgryujk** [comment]
如果被封禁的人没关注贴吧就会失败

**Comment by BreakshadowCN** [comment]
@xfgryujk 用wap和客户端接口吧，电脑版的PMC接口居然真设计成这样了……

**Comment by xfgryujk** [comment]
噗，WAP接口居然真的可以，已经改成WAP接口了
