### ISSUE TITLE
作者大大棒棒哒，提几个建议吧

### ISSUE THREAD

**Issue by tjsky** [xfgryujk/TiebaManager#7]
首先是感谢作者提供了优秀的软件~~

我看到了白名单和删封前确认，这个是很需要的功能。

有几个建议

1、有删帖封禁权限的不仅仅是大吧和小吧，还有一个----“语音小编”他和小吧的权限一致。
希望加入这个的检测，不清楚你是如何做的检测，不过在写JS时，我一般是去检测网页里有没有.tbAdminManage（就是那个进入“贴吧后台按钮”）元素确定ID是不是吧务

2、可否加入坟贴检测呢？一般爆吧都是挖坟吧。
逻辑上就是：
扫首页的帖子时，多扫一个发帖时间，
如果发帖时间晚于用户设置日期，不进入坟贴检测环节。
如果发现帖子发帖时间早于某日期，
检测最后回复人回复时间是否晚于用户设置日期，
进入删封流程。
同时记录下这个帖子的回复数，
如果下次刷新和上次回复数一致就不再进入坟贴检测，
发现回复数增大，记录最后回复人，
进入删封流程。

3、名单能批量添加不，一行一条。信任名单太长，一条条加进去好累呢。

以下是脑洞，自己也没有想好如何做。

4、加入最后回复人等级检测，这样可以限制低等级回帖（不现实，我自己感觉太费带宽了，我习惯用wap接口扫内容省流量，但这里不显示等级，www接口又太费带宽）

5、锁会员，拉取贴吧会员列表，锁死最后一个人，新关注的一律拉黑。（被爆吧时，有时有效果）

6、基于等级检测可以做个，低等级发图检测。大部分广告ID都低等级甩一堆图出来。

**Comment by xfgryujk** [comment]
2因为贴吧有楼中楼要检测最后回复人难度很大而且不能保证挖坟的贴没被删除
5可以用超级功能的批量拉黑
_(:з」∠)_等我放假了一定填坑

**Comment by BreakshadowCN** [comment]
删封权限检测好做。PageData.power数组里什么都有……

**Comment by tjsky** [comment]
@xfgryujk 
感觉比较迫切还是等级检测。
最近用图片爆吧的流行起来了
随机ID，随机图片，随机内容。

想了好久，感觉只能检测到主题/回复带图片尺寸较大（排除表情）时检测回帖者等级，低于一个设置值时，提交违规。

**Comment by xfgryujk** [comment]
打算今天开始做等级检测...
