### ISSUE TITLE
信任主题和信任ID貌似失效了

### ISSUE THREAD

**Issue by tjsky** [xfgryujk/TiebaManager#9]
![default](https://cloud.githubusercontent.com/assets/7272911/15810570/c05c7ed8-2bd2-11e6-89b3-5f93e993d1e3.jpg)

主题ID和发帖ID都是信任的，但还是被扫出来了。

但只会在主题标题含有违禁内容这一种情况下会被扫出来。

感觉上只在电脑出现卡顿时，偶尔会出现这个问题。

**Comment by xfgryujk** [comment]
其实这个信任主题是不会扫描里面的帖子，不代表主题不会违规...
信任ID发来看看

**Comment by tjsky** [comment]
等下次出现了给你发。。这情况几天到一周才会出一次。。抓不准触发条件

**Comment by tjsky** [comment]
好了，知道为什么出这个问题了。

如果帖子C在A方案里是信任，在B不是信任。
A方案有匹配帖子C里内容的规则，B里没有匹配帖子C里内容的规则

从A方案切换到B方案，帖子C因为不是信任所以会被扫描，在扫描了一半时再切换到A，
就会用A方案的规则去匹配C的内容，等于是绕过了信任主题。
So。。一堆违规内容。。。

**Comment by xfgryujk** [comment]
这就很尴尬了，其实我对热切换做的保护不多
